# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: battle_description.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'battle_description.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x62\x61ttle_description.proto\"C\n\x12\x44\x65scriptionRequest\x12\x15\n\rfirst_char_id\x18\x01 \x01(\t\x12\x16\n\x0esecond_char_id\x18\x02 \x01(\t\"1\n\x13\x44\x65scriptionResponse\x12\x1a\n\x12\x62\x61ttle_description\x18\x01 \x01(\t2V\n\x12\x44\x65scriptionService\x12@\n\x13GenerateDescription\x12\x13.DescriptionRequest\x1a\x14.DescriptionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'battle_description_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DESCRIPTIONREQUEST']._serialized_start=28
  _globals['_DESCRIPTIONREQUEST']._serialized_end=95
  _globals['_DESCRIPTIONRESPONSE']._serialized_start=97
  _globals['_DESCRIPTIONRESPONSE']._serialized_end=146
  _globals['_DESCRIPTIONSERVICE']._serialized_start=148
  _globals['_DESCRIPTIONSERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
