# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import actions_processor_llm_pb2 as actions__processor__llm__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in actions_processor_llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActionProcessorServiceStub(object):
    """Сервис, обрабатывающий действия и возвращающий сгенерированный JSON
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessActions = channel.unary_unary(
                '/ActionProcessorService/ProcessActions',
                request_serializer=actions__processor__llm__pb2.ActionList.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)


class ActionProcessorServiceServicer(object):
    """Сервис, обрабатывающий действия и возвращающий сгенерированный JSON
    """

    def ProcessActions(self, request, context):
        """RPC метод, принимающий список действий и возвращающий произвольную JSON-структуру
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActionProcessorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessActions': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessActions,
                    request_deserializer=actions__processor__llm__pb2.ActionList.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ActionProcessorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ActionProcessorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActionProcessorService(object):
    """Сервис, обрабатывающий действия и возвращающий сгенерированный JSON
    """

    @staticmethod
    def ProcessActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ActionProcessorService/ProcessActions',
            actions__processor__llm__pb2.ActionList.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
