# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actions_processor_llm.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'actions_processor_llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61\x63tions_processor_llm.proto\x1a\x1cgoogle/protobuf/struct.proto\"%\n\x06\x41\x63tion\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"&\n\nActionList\x12\x18\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\x07.Action2P\n\x16\x41\x63tionProcessorService\x12\x36\n\x0eProcessActions\x12\x0b.ActionList\x1a\x17.google.protobuf.Structb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actions_processor_llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTION']._serialized_start=61
  _globals['_ACTION']._serialized_end=98
  _globals['_ACTIONLIST']._serialized_start=100
  _globals['_ACTIONLIST']._serialized_end=138
  _globals['_ACTIONPROCESSORSERVICE']._serialized_start=140
  _globals['_ACTIONPROCESSORSERVICE']._serialized_end=220
# @@protoc_insertion_point(module_scope)
